# Generated by Django 3.0.2 on 2020-01-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabApi.Driver', verbose_name='driver'),
        ),
    ]
